/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as DataSourcesRouteImport } from './routes/data-sources'
import { Route as DocumentQaRouteImport } from './routes/document-qa'
import { Route as KnowledgeBaseRouteImport } from './routes/knowledge-base'
import { Route as OverviewRouteImport } from './routes/overview'
import { Route as TextToSqlRouteImport } from './routes/text-to-sql'
import { Route as UsersRouteImport } from './routes/users'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DataSourcesRoute = DataSourcesRouteImport.update({
  id: '/data-sources',
  path: '/data-sources',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentQaRoute = DocumentQaRouteImport.update({
  id: '/document-qa',
  path: '/document-qa',
  getParentRoute: () => rootRouteImport,
} as any)
const KnowledgeBaseRoute = KnowledgeBaseRouteImport.update({
  id: '/knowledge-base',
  path: '/knowledge-base',
  getParentRoute: () => rootRouteImport,
} as any)
const OverviewRoute = OverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => rootRouteImport,
} as any)
const TextToSqlRoute = TextToSqlRouteImport.update({
  id: '/text-to-sql',
  path: '/text-to-sql',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersRoute = UsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/data-sources': typeof DataSourcesRoute
  '/document-qa': typeof DocumentQaRoute
  '/knowledge-base': typeof KnowledgeBaseRoute
  '/overview': typeof OverviewRoute
  '/text-to-sql': typeof TextToSqlRoute
  '/users': typeof UsersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/data-sources': typeof DataSourcesRoute
  '/document-qa': typeof DocumentQaRoute
  '/knowledge-base': typeof KnowledgeBaseRoute
  '/overview': typeof OverviewRoute
  '/text-to-sql': typeof TextToSqlRoute
  '/users': typeof UsersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/data-sources': typeof DataSourcesRoute
  '/document-qa': typeof DocumentQaRoute
  '/knowledge-base': typeof KnowledgeBaseRoute
  '/overview': typeof OverviewRoute
  '/text-to-sql': typeof TextToSqlRoute
  '/users': typeof UsersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/data-sources'
    | '/document-qa'
    | '/knowledge-base'
    | '/overview'
    | '/text-to-sql'
    | '/users'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/data-sources'
    | '/document-qa'
    | '/knowledge-base'
    | '/overview'
    | '/text-to-sql'
    | '/users'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/data-sources'
    | '/document-qa'
    | '/knowledge-base'
    | '/overview'
    | '/text-to-sql'
    | '/users'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  DataSourcesRoute: typeof DataSourcesRoute
  DocumentQaRoute: typeof DocumentQaRoute
  KnowledgeBaseRoute: typeof KnowledgeBaseRoute
  OverviewRoute: typeof OverviewRoute
  TextToSqlRoute: typeof TextToSqlRoute
  UsersRoute: typeof UsersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data-sources': {
      id: '/data-sources'
      path: '/data-sources'
      fullPath: '/data-sources'
      preLoaderRoute: typeof DataSourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/document-qa': {
      id: '/document-qa'
      path: '/document-qa'
      fullPath: '/document-qa'
      preLoaderRoute: typeof DocumentQaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/knowledge-base': {
      id: '/knowledge-base'
      path: '/knowledge-base'
      fullPath: '/knowledge-base'
      preLoaderRoute: typeof KnowledgeBaseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/overview': {
      id: '/overview'
      path: '/overview'
      fullPath: '/overview'
      preLoaderRoute: typeof OverviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/text-to-sql': {
      id: '/text-to-sql'
      path: '/text-to-sql'
      fullPath: '/text-to-sql'
      preLoaderRoute: typeof TextToSqlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  DataSourcesRoute: DataSourcesRoute,
  DocumentQaRoute: DocumentQaRoute,
  KnowledgeBaseRoute: KnowledgeBaseRoute,
  OverviewRoute: OverviewRoute,
  TextToSqlRoute: TextToSqlRoute,
  UsersRoute: UsersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
